site_name: Radview Docs
nav: 
  - Home: index.md
  - Dashboard Guide: 
    - Introduction: dashboard/introduction.md
    - Installing WebLOAD Dashboard: dashboard/installing-webload.md
    - Getting Started: dashboard/getting-started.md
    - Managing Tests: dashboard/managing-tests.md
    - Managing Sessions: dashboard/managing-sessions.md
    - Managing Resourses: dashboard/managing-resources.md
    - Using Dashboards: dashboard/using-dashboards.md
    - Customizing a Dashboard: dashboard/customizing-dashboard.md
    - Managing Dashboards: dashboard/managing-dashboards.md
    - Sharing a Dashboard or Panel: dashboard/sharing-a-dashboard-or-panel.md
    - Creating and Playing a Playlist: dashboard/creating-and-playing-a-playlist.md
    - Managing Load Generators: dashboard/managing-load-generators.md
    - Managing Organizations, Users and Admins: dashboard/managing-organizations-users-and-admins.md
    - Appendix: dashboard/appendix.md
theme: readthedocs